### ISSUE TITLE
Error with .jsx extension

### ISSUE THREAD

**Issue by Bernardstanislas** [brunch/react-brunch#12]
Brunch build fails with `.jsx` files, with the following error :

``` bash
ERROR [TypeError: Cannot assign to read only property 'sourceMap' of #<Object>]
undefined
ERROR [TypeError: Cannot assign to read only property 'sourceMap' of #<Object>]
undefined
...
error: Compiling of 'file1.jsx' failed. TypeError: Cannot assign to read only property 'sourceMap' of #<Object> ; Compiling of 'file2.jsx' failed. TypeError: Cannot assign to read only property 'sourceMap' of #<Object> ; ...
```

When file extensions are replaced by `.js` (with the same content as the `.jsx` version), build passes.

Node version `0.12.2`
Npmversion `2.7.4`
Brunch version `1.8.3`
React-brunch version `1.0.9`

Thank you !

**Comment by denysdovhan** [comment]
@Bernardstanislas, hi!

If this issue is still actual, please update your Node.js, Brunch and dependencies to the latest versions — this should help.

Also, keep in mind that this plugin is going to be deprecated. That means it's better to get rid of it and start to use [`babel-brunch`](https://github.com/babel/babel-brunch) with [`babel-preset-react`](https://github.com/babel/babel/tree/master/packages/babel-preset-react). Take a look at [`with-react`](https://github.com/brunch/with-react) skeleton for inspiration.
